# Steps for building the project.
# These are common in PR builds and release builds

steps:
- task: NodeTool@0
  displayName: 'Use Node 16.x'
  inputs:
    versionSpec: 16.x

# Build the project
- task: PowerShell@2
  displayName: 'Build the project'
  inputs:
    filePath: '$(tasksRoot)/build.ps1'
    arguments: 'BuildForProduction'

# Run the tests
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages for test project'
  inputs:
    restoreSolution: '$(tasksRoot)/test/assets/HelloWorldUWPApp/HelloWorldApp.sln'

- pwsh: |
    npx mocha
  displayName: 'Run the tests'
  workingDirectory: '$(tasksRoot)'
  env:
    SYSTEM_CULTURE: 'en-US'

